baseURL = 'https://erichaag.dev/'
enableGitInfo = true
languageCode = 'en-us'
theme = 'LoveIt'
title = 'Eric Haag'
googleAnalytics = "G-HQ6GQ1GRQR"

[author]
email = "eah0592@gmail.com"
link = "https://github.com/erichaagdev"
name = "Eric Haag"

[params]
dateFormat = "Jan 02, 2006"
description = "Senior Software Engineer at Gradle, Inc."
gitRepo = "https://github.com/erichaagdev/erichaag.dev"
title = "Eric Haag"

[params.header.title]
name = "Eric Haag"

[params.footer]
hugo = false

[params.app]
title = "Eric Haag"

[params.home.profile]
avatarURL = "/images/avatar.png"
subtitle = "Senior Software Engineer at Gradle, Inc."

[params.social]
Email = "eah0592@gmail.com"
GitHub = "https://github.com/erichaagdev"
Linkedin = "https://www.linkedin.com/in/erichaagdev"
Twitter = "https://twitter.com/erichaagdev"

[params.page.share]
HackerNews = false
Line = false
Linkedin = true
Reddit = true
Weibo = false

[params.analytics]
enable = true

[params.analytics.google]
id = "G-HQ6GQ1GRQR"
