[versions]
firebase = "13.6.0"
hugo = "0.124.1"
hugoTheme = "0.2.11"
junit = "5.10.2"
springBoot = "3.0.0"

[libraries]
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
springBoot = { module = "org.springframework.boot:spring-boot", version.ref = "springBoot" }
