[versions]
apacheCommonsText = "1.11.0"
commonCustomUserDataGradlePlugin = "1.13"
develocityGradlePlugin = "3.16.2"
firebase = "13.6.0"
hugo = "0.124.1"
hugoTheme = "0.2.11"
junit = "5.10.2"
springBoot = "3.2.4"
springCloud = "2023.0.1"
springDependencyManagementGradlePlugin = "1.1.4"

[libraries]
apacheCommonsText = { module = "org.apache.commons:commons-text", version.ref = "apacheCommonsText" }
commonCustomUserDataGradlePlugin = { module = "com.gradle.common-custom-user-data-gradle-plugin:com.gradle.common-custom-user-data-gradle-plugin.gradle.plugin", version.ref = "commonCustomUserDataGradlePlugin" }
develocityGradlePlugin = { module = "com.gradle.enterprise:com.gradle.enterprise.gradle.plugin", version.ref = "develocityGradlePlugin" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
springBootDependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
springCloudDependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "springCloud" }
springDependencyManagementGradlePlugin = { module = "io.spring.dependency-management:io.spring.dependency-management.gradle.plugin", version.ref = "springDependencyManagementGradlePlugin" }
