[versions]
apacheCommonsText = "1.11.0"
commonCustomUserData = "1.13"
develocity = "3.16.2"
firebase = "13.6.0"
hugo = "0.124.1"
hugoTheme = "0.2.11"
junit = "5.10.2"
springBoot = "3.2.4"
springCloud = "2023.0.1"
springDependencyManagement = "1.1.4"
wrapperUpgrade = "0.11.4"


[libraries]
apacheCommonsText = { module = "org.apache.commons:commons-text", version.ref = "apacheCommonsText" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
springBootDependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
springCloudDependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "springCloud" }

[plugins]
commonCustomUserData = { id = "com.gradle.common-custom-user-data-gradle-plugin", version.ref = "commonCustomUserData" }
develocity = { id = "com.gradle.enterprise", version.ref = "develocity" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
wrapperUpgrade = { id = "org.gradle.wrapper-upgrade", version.ref = "wrapperUpgrade" }
