baseURL = "https://erichaag.dev"
languageCode = "en-us"
title = "Eric Haag"
theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "posts"
name = "Posts"
title = "Blog posts"
url = "/posts"
weight = 1

[params]
title = "Eric Haag"
description = "Eric Haag's Personal Site"
favicon = "/logo.png"
useBootstrapCDN = false
mathjax = false
animate = true

[params.font]
fontSize = "1rem"
fontWeight = 400
lineHeight = 1.5
textAlign = "left"

[params.color]
textColor = "#4c4f69" # Text
secondaryTextColor = "#5c5f77" # Subtext 1
backgroundColor = "#eff1f5" # Base
secondaryBackgroundColor = "#dce0e8" # Crust
primaryColor = "#5c5f77" # Subtext 1
secondaryColor = "#dce0e8" # Crust
linkColor = "#1e66f5" # Blue

[params.color.darkmode]
textColor = "#cdd6f4" # Text
secondaryTextColor = "#bac2de" # Subtext 1
backgroundColor = "#1e1e2e" # Base
secondaryBackgroundColor = "#11111b" # Crust
primaryColor = "#bac2de" # Subtext 1
secondaryColor = "#11111b" # Crust
linkColor = "#89b4fa" # Blue

[params.navbar]
align = "ms-auto"
brandName = "Eric Haag"
disableSearch = true

[params.navbar.stickyNavBar]
enable = true
showOnScrollUp = true

[params.navbar.menus]
disableAbout = true
disableExperience = true
disableEducation = true
disableProjects = true
disableAchievements = true
disableContact = true

[params.hero]
enable = true
intro = "Hi, my name is"
title = "Eric."
subtitle = "I like building things"
content = "Championing Developer Productivity Engineering, fueled by a love for Java, Kotlin, Spring Boot, and Gradle."
image = "/images/avatar.jpg"

[params.hero.bottomImage]
enable = true

[params.hero.button]
enable = false
name = "Resume"
url = "#"
download = true
newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/erichaagdev"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin"
url = "https://linkedin.com/in/erichaagdev"

[params.about]
enable = false
title = "About Me"
image = "/images/avatar.jpg"
content = """
I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA.

I am currently working on a project that will be used to help people find the best way to get around the city."""

[params.about.skills]
enable = false
title = "Here are a few technologies I've been working with recently:"
items = [ "HTML", "CSS", "JavaScript", "React", "Node", "Express" ]

[params.experience]
enable = false

[[params.experience.items]]
job = "Senior Software Developer"
company = "Facebook"
companyUrl = "https://example.com"
date = "Jan 2022 - present"
content = "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

[params.experience.items.featuredLink]
enable = false
name = "View the project"
url = "https://example.com"

[[params.experience.items]]
job = "Software Developer"
company = "Amazon"
companyUrl = "https://example.com"
date = "Sep 2020 - Dec 2021"
content = """
I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

- Lead backend developer for a product.
- Created a frontend design for a product.
"""

[params.experience.items.featuredLink]
enable = false
url = "https://example.com"

[params.experience.items.info]
enable = false
content = "I worked as a software developer for more than one year in Amazon."

[[params.experience.items]]
job = "Junior Software Developer"
company = "Apple"
companyUrl = "https://example.com"
date = "Jan 2020 - Aug 2020"
content = """
I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

- Lead backend developer for a product.
- Created a frontend design for a product.
"""

[params.experience.items.info]
enable = false

[params.experience.items.featuredLink]
enable = false
url = "https://example.com"

[[params.experience.items]]
job = "UI/UX Designer"
company = "Netflix"
companyUrl = "https://example.com"
date = "June 2017 - Nov 2019"
content = """
I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

- Lead backend developer for a product.
- Created a frontend design for a product.
"""

[params.experience.items.featuredLink]
enable = false
url = "https://example.com"

[[params.experience.items]]
job = "Product Designer"
company = "Google"
companyUrl = "https://example.com"
date = "Feb 2016 - Mar 2017"
content = "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

[params.education]
enable = false
index = false

[[params.education.items]]
title = "Master of Business Administration"
date = "2013 - 2015"
GPA = "3.8 out of 5.0"
content = """
Extracurricular Activities
  - Lorem ipsum dolor sit amet consectetur adipisicing elit.
  - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique."""

[params.education.items.school]
name = "University of California, Berkeley"
url = "https://example.org"

[[params.education.items]]
title = "Bachelor of Science in Computer Science"
date = "2009 - 2013"
GPA = "3.9 out of 5.0"
content = """
I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
- [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
- Face mask detection using a single convolutional neural network.

Extracurricular Activities
  - Lorem ipsum dolor sit amet consectetur adipisicing elit.
  - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique."""

[params.education.items.school]
name = "Massachusetts Institute of Technology"
url = "https://example.org"

[params.education.items.featuredLink]
enable = false
name = "My academic record"
url = "https://example.com"

[[params.education.items]]
title = "High School"
GPA = "4.2 out of 5.0"

[params.education.items.school]
name = "Thomas Jefferson High School for Science and Technology."
url = "https://example.org"

[params.education.items.featuredLink]
enable = false
url = "https://example.com"

[params.achievements]
enable = false

[[params.achievements.items]]
title = "Google kickstart runner"
content = "I solved all problems with optimal solution."
url = "https://example.com"
image = "/images/achievment.jpg"

[[params.achievements.items]]
title = "Facebook Hackathon Winner"
content = "Developed a product using Artificial Intelligence."
image = "/images/achievment.jpg"

[[params.achievements.items]]
title = "Hugo Profile"
content = "Developed a theme and getting 1K+ downloads per month."
url = "https://github.com/gurusabarish/hugo-profile"
image = "/images/achievment.jpg"

[[params.achievements.items]]
title = "Microsoft Imagine Runner"
content = "We are developed a product which can help others."

[[params.achievements.items]]
title = "Google Summer of Code"
content = "Contributed to a open source project."
url = "https://example.com"

[params.projects]
enable = false

[[params.projects.items]]
title = "Hugo Profile"
content = "A highly customizable and mobile first Hugo template for personal portfolio and blog."
image = "/images/projects/profile.png"
badges = [ "Hugo", "Bootstrap", "Javascript" ]

[params.projects.items.featured]
name = "Demo"
link = "https://hugo-profile.netlify.app"

[[params.projects.items.links]]
icon = "fa fa-envelope"
url = "mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f"

[[params.projects.items.links]]
icon = "fab fa-github"
url = "https://github.com/gurusabarish/hugo-profile"

[[params.projects.items.links]]
icon = "fab fa-twitter"
url = "https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile"

[[params.projects.items]]
title = "Image Converter"
content = "A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django."
image = "/images/projects/converter.jpg"
badges = [ "Django", "Bootstrap" ]

[params.projects.items.featured]
name = "Demo"
link = "https://django-converter.herokuapp.com"

[[params.projects.items.links]]
icon = "fab fa-github"
url = "https://github.com/gurusabarish/converter"

[[params.projects.items]]
title = "Hugo Profile V2"
content = "A clean and simple Hugo template for personal portfolio and blog."
image = "/images/projects/profile2.jpg"
badges = [ "Hugo", "Bootstrap", "Javascript" ]

[params.projects.items.featured]
name = "Demo V2"
link = "https://hugo-profile-2.netlify.app"

[[params.projects.items.links]]
icon = "fab fa-github"
url = "https://github.com/gurusabarish/HugoProfileV2"

[params.contact]
enable = false
content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
btnName = "Mail me"
btnLink = "mailto:gurusabarisha@gmail.com"

[params.footer.recentPosts]
path = "posts"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

#[params.footer.socialNetworks]
#github = "https://github.com/erichaagdev"
#linkedin = "https://linkedin.com/erichaagdev"
#twitter = "https://twitter.com"
#instagram = "https://instagram.com"
#facebook = "https://facebook.com"

[params.listPages]
disableFeaturedImage = false

[params.singlePages.readTime]
enable = true
content = "min read"

[params.singlePages.scrollprogress]
enable = true

[params.terms]
read = "Read"
toc = "Table Of Contents"
copyright = "All rights reserved"
pageNotFound = "Page not found"
emailText = "Check out this site"
social = "Share"

[params.datesFormat]
article = "Jan 2, 2006"
articleList = "Jan 2, 2006"
articleRecent = "Jan 2, 2006"
