# Theme documentation: https://hugoloveit.com/theme-documentation-basics/#3-configuration

baseURL = "https://erichaag.dev/"
enableGitInfo = true
languageCode = "en-us"
title = "Eric Haag"
googleAnalytics = "G-HQ6GQ1GRQR"

[author]
email = "eah0592@gmail.com"
link = "https://github.com/erichaagdev"
name = "Eric Haag"

[[menu.main]]
weight = 1
identifier = "posts"
name = "Posts"
title = "Posts"
url = "/posts/"

[[menu.main]]
weight = 2
identifier = "github"
pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
title = "GitHub"
url = "https://github.com/erichaagdev/erichaag.dev"

[markup.highlight]
guessSyntax = false
lineNos = true
lineNumbersInTable = true
noClasses = false

[markup.tableOfContents]
startLevel = 2
endLevel = 6

[params]
dateFormat = "Jan 02, 2006"
description = "Developer Productivity Engineering advocate with a passion for Java, Kotlin, Spring Boot, and Gradle."
gitRepo = "https://github.com/erichaagdev/erichaag.dev"
title = "Eric Haag"

[params.header.title]
name = "Eric Haag"

[params.footer]
hugo = false

[params.app]
title = "Eric Haag"

[params.home.profile]
avatarURL = "/images/avatar.png"
subtitle = "Developer Productivity Engineering advocate with a passion for Java, Kotlin, Spring Boot, and Gradle."
typeit = false

[params.section]
dateFormat = "Jan 02"

[params.list]
dateFormat = "Jan 02"

[params.social]
Email = "eah0592@gmail.com"
GitHub = "erichaagdev"
Linkedin = "erichaagdev"
Twitter = "erichaagdev"

[params.page.toc]
auto = false

[params.page.share]
HackerNews = false
Line = false
Linkedin = true
Reddit = true
Weibo = false

[params.analytics]
enable = true

[params.analytics.google]
id = "G-HQ6GQ1GRQR"
