name: Build & deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_deploy:
    name: Build & deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Build & deploy
        run: ./gradlew deployFirebase
