name: Build & deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_deploy:
    name: Build & deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Setup Firebase
        uses: ./.github/actions/setup-firebase
        with:
          version: 11.18.0
      - name: Setup Hugo
        uses: ./.github/actions/setup-hugo
        with:
          version: 0.108.0
      - name: Build site
        run: hugo
      - name: Deploy site
        run: firebase deploy --project "${FIREBASE_PROJECT}"
        env:
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
