name: Build & deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_deploy:
    name: Build & deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Setup Firebase
        uses: pocket-apps/action-setup-firebase@v2
        with:
          firebase-token: <unused>
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Build
        run: hugo
      - name: Deploy
        run: firebase deploy --project "$FIREBASE_PROJECT"
        env:
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
