name: Deploy to Firebase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  firebase_deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Deploy to Firebase
        run: ./gradlew deployFirebase
